### ISSUE TITLE
Suggested VTK-m commit does not compile on Summit, nor CUDA 10

### ISSUE THREAD

**Issue by NAThompson** [Alpine-DAV/vtk-h#115]
The suggested commit for VTK-m `403bca94c7166e9428119c6d1cc8d40f81583faf` does not compile with CUDA 10.1, which is the native version on Summit.

Which VTK-m commit is recommended that compiles with CUDA 10.1 on Summit?

**Comment by cyrush** [comment]
that may be stale -- sorry about that -- I'll change that link.

This is what you need:

vtkm branch='master' commit='77f17450ba8bfbe09a9570ef9c5cdc275061f34f'

Here is the reliable source:


https://ascent.readthedocs.io/en/latest/BuildingAscent.html#building-ascent-and-third-party-dependencies

**Comment by cyrush** [comment]
I updated the readme -- sorry again!

**Comment by NAThompson** [comment]
@cyrush : Thanks so much for the quick response!
