### ISSUE TITLE
vtkh build errors with Intel 18 on LLNL toss_3 machines

### ISSUE THREAD

**Issue by lee-busby** [Alpine-DAV/vtk-h#147]
My problem looks very similar to #142, so I won't repeat extensive output.  This is on rzalastor.  My vtkm build with the same compiler goes through fine.  I am also able to build all three of vtkm, vtkh, ascent using gnu-7.3.0 or (amazingly) nvcc + xlc++ on rzansel, with the same basic cmake recipes, which I will of course be happy to reproduce on request.  These results are against current recommended revisions of those packages from the Ascent build instructions.  Thanks -- Lee Busby.

**Comment by cyrush** [comment]
Thanks @lee-busby, confirms some issue with use of vtk-m (delayed compile until use features in vtk-h) and intel 18. We will investigate.

**Comment by mclarsen** [comment]
The latest release updated vtkm, which corrected the problem
