### ISSUE TITLE
Contour tree bugs

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/vtk-h#156]
https://github.com/Alpine-DAV/vtk-h/blob/828a63ff6e82e695eecb569b4346c4b36b599395/src/vtkh/filters/ContourTree.cpp#L192
If there is one rank, split dim is -1 and later causes references bad memory. I don't know what the value should be in this case.

@ghweber

**Comment by mclarsen** [comment]
Additionally, there is apparently deadlock inside the the contour tree filter inside vtkm. This is likely due to the new changes to array portals now creating locks everywhere and the unit testing not testing everything. I am going to disable the contour tree testing until this is resolved.

**Comment by mclarsen** [comment]
There have been some fixes to vtkm, but they have not corrected the deadlock in the contour tree code. Who knows what landmines await that have not been found, so I am going to request a vtkm option to disable the locking completely.

**Comment by ghweber** [comment]
@David-Camp can you please take a look at these problems?

**Comment by mclarsen** [comment]
I think the locking issues have been resolved, but I don't know where we currently stand.

**Comment by David-Camp** [comment]
Hi Matt,

I am going to look at the Contour tree bugs #156 issue.

David

**Comment by mclarsen** [comment]
In debug mode:

```
/usr/WS2/larsen30/marbl_6_17_20/vtkh-4518e03/src/vtkh/filters/ContourTree.cpp(373): error: class "vtkm::worklet::contourtree_augmented::ContourTree" has no member "arcs"
      std::cout<<"Acrs : " << filter.GetContourTree().arcs.GetNumberOfValues() <<std::endl;
```

This is happening because the member is not there and because DIY inside vtkm is giving us a public compile definition that defines `DEBUG`
