### ISSUE TITLE
is_trivially_copyable vs clang

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/vtk-h#163]
derived from:

https://github.com/Alpine-DAV/vtk-h/blob/8b2a0c47a4cbafb27298d725bda2532f4cd5c80f/src/vtkh/filters/communication/MemStream.h#L101

```
#include <type_traits>


int main(int argc, char ** argv)
{

#if (defined(__clang__) && !defined(__ppc64__)) || (defined(__GNUC__) && __GNUC__ >= 5)
    static_assert(std::is_trivially_copyable<int>::value, "Default serialization works only for trivially copyable types");
#endif

}
```

the above only works with:

`clang++ -stdlib=libc++ test.cpp  -o here`

should skip the `is_trivially_copyable` for clang, or is there something we need to do in our cmake to enable use of `-stdlib=libc++`. What are the downstream implications?

**Comment by mclarsen** [comment]
If we only add the check for GCC > 5, then anything added that fails `is_trivially_copyable` will fail ci.
