### ISSUE TITLE
allow vtk-h to use external blt

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/vtk-h#96]
like ascent and conduit, needed for codes that share blt across several packages

**Comment by mclarsen** [comment]
How does this work when the external BLT is too old and does not support cuda object libs?

**Comment by cyrush** [comment]
it will fail :-)

Folks that want this are aware of this failure mode. 

The main motivation is to use BLT single external package, and avoid submodules cloning issues.

**Comment by cyrush** [comment]
resolved in #107
